#ifndef IPC_GTEST_WORKER_EVS_H_
#define IPC_GTEST_WORKER_EVS_H_
 
#define IPC_GTEST_INT_MAILIST(X) \
   X(IPC_GTEST_INT_MID,             "MAILS TO SHUTDOWN WORKER") \

#define IPC_GTEST_PBC_MAILIST(X) \
   X(IPC_GTEST_PBC_MID, "MAILS TO ANY SUBSCRIBABLE") \

#endif /*IPC_GTEST_WORKER_EVS_H_*/
